//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserFB.Web.ApplyMessage {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblApplyID;
		protected global::System.Web.UI.WebControls.TextBox txtapplicantID;
		protected global::System.Web.UI.WebControls.TextBox txtapproverID;
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtdepartment;
		protected global::System.Web.UI.WebControls.TextBox txtjob;
		protected global::System.Web.UI.WebControls.TextBox txtpermission;
		protected global::System.Web.UI.WebControls.TextBox txtapplyTime;
		protected global::System.Web.UI.WebControls.TextBox txtapplyState;
		protected global::System.Web.UI.WebControls.TextBox txtremark;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
