//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserFB.Web.ApplyMessage {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblApplyID;
	protected global::System.Web.UI.WebControls.Label lblapplicantID;
	protected global::System.Web.UI.WebControls.Label lblapproverID;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lbldepartment;
	protected global::System.Web.UI.WebControls.Label lbljob;
	protected global::System.Web.UI.WebControls.Label lblpermission;
	protected global::System.Web.UI.WebControls.Label lblapplyTime;
	protected global::System.Web.UI.WebControls.Label lblapplyState;
	protected global::System.Web.UI.WebControls.Label lblremark;


       
    }
}
