//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserFB.Web.Distribution {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lbldistributionID;
		protected global::System.Web.UI.WebControls.TextBox txtfeedbackID;
		protected global::System.Web.UI.WebControls.TextBox txtdescription;
		protected global::System.Web.UI.WebControls.TextBox txtdistributionTime;
		protected global::System.Web.UI.WebControls.TextBox txtadminID;
		protected global::System.Web.UI.WebControls.TextBox txtassignerID;
		protected global::System.Web.UI.WebControls.TextBox txtstate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
