//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserFB.Web.Distribution {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbldistributionID;
	protected global::System.Web.UI.WebControls.Label lblfeedbackID;
	protected global::System.Web.UI.WebControls.Label lbldescription;
	protected global::System.Web.UI.WebControls.Label lbldistributionTime;
	protected global::System.Web.UI.WebControls.Label lbladminID;
	protected global::System.Web.UI.WebControls.Label lblassignerID;
	protected global::System.Web.UI.WebControls.Label lblstate;


       
    }
}
