//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserFB.Web.Feedback {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblfeedbackID;
		protected global::System.Web.UI.WebControls.TextBox txtUserID;
		protected global::System.Web.UI.WebControls.TextBox txtfeedbackTime;
		protected global::System.Web.UI.WebControls.TextBox txtcategoryID;
		protected global::System.Web.UI.WebControls.TextBox txtInfo;
		protected global::System.Web.UI.WebControls.TextBox txtcontact;
		protected global::System.Web.UI.WebControls.TextBox txtisInvalid;
		protected global::System.Web.UI.WebControls.TextBox txtsolutionState;
		protected global::System.Web.UI.WebControls.TextBox txthandler;
		protected global::System.Web.UI.WebControls.TextBox txtremark;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
