//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserFB.Web.Feedback {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblfeedbackID;
	protected global::System.Web.UI.WebControls.Label lblUserID;
	protected global::System.Web.UI.WebControls.Label lblfeedbackTime;
	protected global::System.Web.UI.WebControls.Label lblcategoryID;
	protected global::System.Web.UI.WebControls.Label lblInfo;
	protected global::System.Web.UI.WebControls.Label lblcontact;
	protected global::System.Web.UI.WebControls.Label lblisInvalid;
	protected global::System.Web.UI.WebControls.Label lblsolutionState;
	protected global::System.Web.UI.WebControls.Label lblhandler;
	protected global::System.Web.UI.WebControls.Label lblremark;


       
    }
}
